### ISSUE TITLE
Gandalf.app and gandalf.app Compiling on macOS and on Linux is different: macOS isn't case sensitive?

### ISSUE THREAD

**Issue by ann0see** [EthanRDoesMC/gandalf#52] opened 2017-05-22 20:41 UTC
Hopefully not a wontfix. So Linux usually is case sensitive. https://www.louiewong.com/archives/226 That means gandalf.app ≠ Gandalf.app. 
But in macOS that's different by default (?). So if you name the Gandalf application Gandalf.app but in build.sh you copy gandalf.app it won't succeed on Linux, but on macOS. 
Somehow @mehulrao 's (sorry for the ping) app is uploaded in two .app folders: gandalf.app and Gandalf.app. Now on my machine (and on iOS) will only copy Gandalf.app to the deb. But: on macOS that seems to be different. 
We need to unify the names. Everything in lowercase would be good, but first we must find out why there are 2 g/Gandalf.app s. I have currently fixed the G/gandalf.app issue temporarily. 
*Please try to compile Gandalf on a Mac...*

On GitHub online you can check if there are 2 .app folders. 

Sorry for this bad explanation. Hopefully you understand me.

**Comment by mehulrao** [comment] 2017-08-09 12:05
The 2 gandalf.apps are caused by an older version. (I think) it should be fixed now. The easiest thing to do is delete both, then reinstall gandalf @ann0see

**Closed** 2017-08-11 08:56 UTC
Labels: enhancement
